window.SITE_CONTENT = {
  common: {
    ja: {
      site_name: "株式会社富鯉",
      site_wordmark: "FUKOI",
      nav_projects: "PROJECTS",
      nav_studio: "STUDIO",
      nav_contact: "CONTACT",
      lang_ja: "JP",
      lang_en: "EN",
      lang_zh: "中",
      company_info_title: "COMPANY INFO",
      company_name_label: "会社名",
      company_name_value: "株式会社富鯉",
      company_address_label: "所在地",
      company_address_value: "東京都品川区東五反田一丁目8番1号 シルバープラザ五反田",
      company_business_label: "事業内容",
      company_business_value: "ゲーム開発・運営・海外市場展開",
      company_contact_label: "お問い合わせ",
      company_contact_value: "contact@fukoi.co",
      company_established_label: "設立",
      company_established_value: "2024年6月21日",
      company_languages_label: "言語",
      company_languages_value: "JP / EN / 中文",
      footer_brand_name: "FURI STUDIO",
      footer_company_name: "株式会社富鯉",
      footer_contact_heading: "CONTACT",
      footer_location_heading: "LOCATION",
      footer_copy: "&copy; 2024–2026 株式会社富鯉"
    },
    en: {
      site_name: "Fukoi Inc.",
      site_wordmark: "FUKOI",
      nav_projects: "PROJECTS",
      nav_studio: "STUDIO",
      nav_contact: "CONTACT",
      lang_ja: "JP",
      lang_en: "EN",
      lang_zh: "中",
      company_info_title: "COMPANY INFO",
      company_name_label: "Company",
      company_name_value: "Fukoi Inc.",
      company_address_label: "Location",
      company_address_value: "Silver Plaza Gotanda, 1-8-1 Higashi-Gotanda, Shinagawa-ku, Tokyo",
      company_business_label: "Business",
      company_business_value: "Game development, operations, and overseas market expansion",
      company_contact_label: "Contact",
      company_contact_value: "contact@fukoi.co",
      company_established_label: "Established",
      company_established_value: "June 21, 2024",
      company_languages_label: "Languages",
      company_languages_value: "JP / EN / 中文",
      footer_brand_name: "FURI STUDIO",
      footer_company_name: "Fukoi Inc.",
      footer_contact_heading: "CONTACT",
      footer_location_heading: "LOCATION",
      footer_copy: "&copy; 2024–2026 Fukoi Inc."
    },
    zh: {
      site_name: "株式会社富鲤",
      site_wordmark: "FUKOI",
      nav_projects: "项目",
      nav_studio: "公司",
      nav_contact: "联系",
      lang_ja: "JP",
      lang_en: "EN",
      lang_zh: "中",
      company_info_title: "公司信息",
      company_name_label: "公司名",
      company_name_value: "株式会社富鲤",
      company_address_label: "所在地",
      company_address_value: "东京都品川区东五反田一丁目8番1号 シルバープラザ五反田",
      company_business_label: "业务内容",
      company_business_value: "游戏开发、运营及海外市场拓展",
      company_contact_label: "联系邮箱",
      company_contact_value: "contact@fukoi.co",
      company_established_label: "设立",
      company_established_value: "2024年6月21日",
      company_languages_label: "语言",
      company_languages_value: "JP / EN / 中文",
      footer_brand_name: "FURI STUDIO",
      footer_company_name: "株式会社富鲤",
      footer_contact_heading: "联系",
      footer_location_heading: "地址",
      footer_copy: "&copy; 2024–2026 株式会社富鲤"
    }
  },
  home: {
    ja: {
      title: "株式会社富鯉 | Game Development, Operations, and Overseas Markets",
      hero_tag: "GAME DEVELOPMENT / GAME OPERATIONS / OVERSEAS EXPANSION",
      hero_brand_note: "FURI STUDIO / 株式会社富鯉",
      hero_title: "株式会社富鯉",
      hero_subtitle: "株式会社富鯉は、日本に拠点を置く独立法人として、ゲームプロダクトの開発・運営および海外市場展開に取り組んでいます。",
      hero_primary: "PROJECTS",
      hero_secondary: "STUDIO / COMPANY",
      hero_poster_label: "FEATURED PROJECT",
      hero_poster_title: "TACTICAL PIXEL PROJECT",
      hero_poster_copy: "日本市場を見据えた戦術体験とピクセルアート表現を軸に、現在開発を進めている注力プロジェクト。",
      about_title: "ABOUT FUKOI",
      about_body: "株式会社富鯉は、日本に拠点を置く独立法人として、ゲームプロダクトの開発・運営および海外市場展開に取り組んでおります。AI活用を中核としたゲーム開発体制を構築し、複数プロジェクトにおいて実運用を進めています。企画、アート制作、実装、ローカライズ、運営準備を含む一連のプロセスを通じて、良質なゲームコンテンツをより広い市場へ届けることを目指しています。",
      about_info_line: "株式会社富鯉｜ゲーム開発・運営・海外市場展開｜東京都品川区東五反田一丁目8番1号 シルバープラザ五反田｜contact@fukoi.co",
      projects_eyebrow: "PROJECT PORTFOLIO",
      projects_intro: "現在進行中の代表タイトルを、ビジュアルと開発文脈の両面から紹介します。",
      projects_title: "FEATURED TITLES",
      project_primary_visual_note: "01 / TACTICAL PIXEL PROJECT",
      project_primary_status: "IN DEVELOPMENT",
      project_primary_title: "TACTICAL PIXEL PROJECT",
      project_primary_body: "ピクセルアートによる戦場表現と、直感的な戦術体験を軸に構築中の新作プロジェクト。日本市場を見据えたビジュアル表現とゲーム体験の両立を目指し、開発を進めています。",
      project_primary_action: "VIEW PROJECT",
      project_secondary_visual_note: "02 / PROJECT: GOBLIN",
      project_secondary_status: "IN DEVELOPMENT",
      project_secondary_title: "PROJECT: GOBLIN",
      project_secondary_body: "鮮やかで広大なファンタジー世界を舞台に、独自の魔法体系と戦略性を掛け合わせた開発中プロジェクト。世界観表現と継続運営を見据えたプロダクト設計を進めています。",
      project_secondary_action: "VIEW PROJECT",
      company_intro_eyebrow: "COMPANY PRESENCE",
      company_intro_body: "日本市場と海外展開の双方を見据えて開発・運営を進めています。"
    },
    en: {
      title: "Fukoi Inc. | Game Development, Operations, and Overseas Markets",
      hero_tag: "GAME DEVELOPMENT / GAME OPERATIONS / OVERSEAS EXPANSION",
      hero_brand_note: "FURI STUDIO / Fukoi Inc.",
      hero_title: "Fukoi Inc.",
      hero_subtitle: "Fukoi Inc. is an independent company based in Japan, engaged in game development, game operations, and overseas market expansion.",
      hero_primary: "PROJECTS",
      hero_secondary: "STUDIO / COMPANY",
      hero_poster_label: "FEATURED PROJECT",
      hero_poster_title: "TACTICAL PIXEL PROJECT",
      hero_poster_copy: "A focus title now in development, built around pixel-art battlefield drama and a clean tactical read for the Japanese market.",
      about_title: "ABOUT FUKOI",
      about_body: "Fukoi Inc. is an independent company based in Japan, engaged in game product development, operations, and overseas market expansion. We have established an AI-centered game development structure and are applying it in real operations across multiple projects. Through planning, art production, implementation, localization, and launch preparation, we aim to deliver high-quality game content to broader audiences.",
      about_info_line: "Fukoi Inc. | Game development, operations, overseas expansion | Silver Plaza Gotanda, 1-8-1 Higashi-Gotanda, Shinagawa-ku, Tokyo | contact@fukoi.co",
      projects_eyebrow: "PROJECT PORTFOLIO",
      projects_intro: "A selected view of the titles currently in development and the direction behind each one.",
      projects_title: "FEATURED TITLES",
      project_primary_visual_note: "01 / TACTICAL PIXEL PROJECT",
      project_primary_status: "IN DEVELOPMENT",
      project_primary_title: "TACTICAL PIXEL PROJECT",
      project_primary_body: "A new project in development centered on expressive pixel-art battlefields and intuitive tactical pacing, designed with the Japanese market in mind.",
      project_primary_action: "VIEW PROJECT",
      project_secondary_visual_note: "02 / PROJECT: GOBLIN",
      project_secondary_status: "IN DEVELOPMENT",
      project_secondary_title: "PROJECT: GOBLIN",
      project_secondary_body: "An in-development fantasy project blending vivid worldbuilding, a bespoke magic system, and long-term product thinking for sustained operations.",
      project_secondary_action: "VIEW PROJECT",
      company_intro_eyebrow: "COMPANY PRESENCE",
      company_intro_body: "A Japan-based operating structure with products moving toward both domestic and overseas audiences."
    },
    zh: {
      title: "株式会社富鲤 | 游戏开发、运营与海外市场拓展",
      hero_tag: "GAME DEVELOPMENT / GAME OPERATIONS / OVERSEAS EXPANSION",
      hero_brand_note: "FURI STUDIO / 株式会社富鲤",
      hero_title: "株式会社富鲤",
      hero_subtitle: "株式会社富鲤作为设立于日本的独立法人，正在开展游戏产品开发、运营以及海外市场拓展。",
      hero_primary: "项目",
      hero_secondary: "公司介绍",
      hero_poster_label: "FEATURED PROJECT",
      hero_poster_title: "TACTICAL PIXEL PROJECT",
      hero_poster_copy: "当前重点推进中的战术像素项目，围绕更本土化的日式审美与清晰直接的战斗体验展开。",
      about_title: "ABOUT FUKOI",
      about_body: "株式会社富鲤是设立于日本的独立法人，正在开展游戏产品开发、运营以及海外市场拓展。公司已建立以 AI 应用为核心的游戏开发体制，并在多个项目中进入实际运用。通过企划、美术制作、实现、本地化与运营准备等一体化流程，持续推动优质游戏内容进入更广阔的市场。",
      about_info_line: "株式会社富鲤｜游戏开发・运营・海外市场拓展｜东京都品川区东五反田一丁目8番1号 シルバープラザ五反田｜contact@fukoi.co",
      projects_eyebrow: "PROJECT PORTFOLIO",
      projects_intro: "以更接近作品陈列的方式，呈现当前推进中的代表项目与开发方向。",
      projects_title: "精选项目",
      project_primary_visual_note: "01 / TACTICAL PIXEL PROJECT",
      project_primary_status: "开发中",
      project_primary_title: "TACTICAL PIXEL PROJECT",
      project_primary_body: "以像素风战场表现与直观战术体验为核心推进中的新作项目，兼顾日本市场导向与产品表现力。",
      project_primary_action: "查看项目",
      project_secondary_visual_note: "02 / PROJECT: GOBLIN",
      project_secondary_status: "开发中",
      project_secondary_title: "PROJECT: GOBLIN",
      project_secondary_body: "正在开发中的奇幻项目，围绕鲜明世界观、自研魔法体系与可持续运营设计持续推进。",
      project_secondary_action: "查看项目",
      company_intro_eyebrow: "COMPANY PRESENCE",
      company_intro_body: "以日本市场为起点，并同步面向更广区域推进开发与运营布局。"
    }
  },
  studio: {
    ja: {
      title: "STUDIO / COMPANY | 株式会社富鯉",
      hero_tag: "STUDIO / COMPANY",
      hero_title: "株式会社富鯉",
      hero_subtitle: "ゲームプロダクトの開発・運営および海外市場展開に取り組む、日本拠点の独立法人です。",
      narrative_title: "STUDIO / COMPANY",
      narrative_body: "FURI STUDIOは、株式会社富鯉が展開するゲームブランドです。富鯉株式会社は、日本に拠点を置く独立法人として、ゲームプロダクトの開発・運営および海外市場展開に取り組んでおります。AI活用を中核としたゲーム開発体制を構築し、複数プロジェクトにおいて実運用を進めています。コンテンツ制作、ローカライズ、運営準備を含む一連のプロセスを通じて、より多くのユーザーへ魅力あるゲーム体験を届けることを目指しています。",
      studio_identity_title: "BRAND / COMPANY",
      studio_identity_body: "FURI STUDIO / 株式会社富鯉<br>ゲーム開発・運営・海外市場展開",
      initiatives_title: "CURRENT INITIATIVES",
      initiatives_body: "現在、複数のゲームプロジェクトにおいて、AI活用を含む開発フローと運営体制の実装を進めています。企画、アート制作、実装、ローカライズ、運営準備を横断的に連携し、継続的なプロダクト展開に向けた基盤構築を行っています。",
      initiatives_card_1_title: "企画から実装まで",
      initiatives_card_1_body: "ゲーム企画、アート制作、実装を一体で進める体制を構築",
      initiatives_card_2_title: "ローカライズと運営準備",
      initiatives_card_2_body: "日本市場を起点に、運営導線と市場適応を整備",
      initiatives_card_3_title: "複数案件の実運用",
      initiatives_card_3_body: "単発検証ではなく、複数プロジェクトで継続的に運用中",
      page_note: "ACTIVE PROJECTS"
    },
    en: {
      title: "STUDIO / COMPANY | Fukoi Inc.",
      hero_tag: "STUDIO / COMPANY",
      hero_title: "Fukoi Inc.",
      hero_subtitle: "An independent company based in Japan, engaged in game development, operations, and overseas market expansion.",
      narrative_title: "STUDIO / COMPANY",
      narrative_body: "FURI STUDIO is the game brand operated by Fukoi Inc. Fukoi Inc. is an independent company based in Japan, engaged in game product development, operations, and overseas market expansion. We have established an AI-centered game development structure and are applying it in real operations across multiple projects. Through content production, localization, and launch preparation, we aim to deliver compelling game experiences to broader audiences.",
      studio_identity_title: "BRAND / COMPANY",
      studio_identity_body: "FURI STUDIO / Fukoi Inc.<br>Game development, operations, overseas expansion",
      initiatives_title: "CURRENT INITIATIVES",
      initiatives_body: "We are currently implementing development flows and operational structures, including AI-enabled processes, across multiple game projects. Planning, art production, implementation, localization, and launch preparation are being coordinated to build the foundation for sustained product rollout.",
      initiatives_card_1_title: "From planning to implementation",
      initiatives_card_1_body: "A working structure that connects game planning, art production, and implementation",
      initiatives_card_2_title: "Localization and operations readiness",
      initiatives_card_2_body: "Operational and market-readiness systems built with Japan as the starting point",
      initiatives_card_3_title: "Multiple projects in motion",
      initiatives_card_3_body: "Not a one-off experiment, but real execution across multiple projects",
      page_note: "ACTIVE PROJECTS"
    },
    zh: {
      title: "STUDIO / COMPANY | 株式会社富鲤",
      hero_tag: "STUDIO / COMPANY",
      hero_title: "株式会社富鲤",
      hero_subtitle: "一家设立于日本、正在推进游戏开发、运营与海外市场拓展的独立法人。",
      narrative_title: "STUDIO / COMPANY",
      narrative_body: "FURI STUDIO 是株式会社富鲤展开的游戏品牌。株式会社富鲤是设立于日本的独立法人，正在推进游戏产品开发、运营以及海外市场拓展。公司已构建以 AI 应用为核心的游戏开发体制，并在多个项目中进入实际运用。通过内容制作、本地化与运营准备等一体化流程，我们希望向更多用户交付更具吸引力的游戏体验。",
      studio_identity_title: "品牌 / 公司",
      studio_identity_body: "FURI STUDIO / 株式会社富鲤<br>游戏开发・运营・海外市场拓展",
      initiatives_title: "CURRENT INITIATIVES",
      initiatives_body: "目前，公司正在多个游戏项目中推进包含 AI 应用在内的开发流程与运营体制建设。围绕企划、美术制作、实现、本地化与运营准备，持续进行跨环节协同，以建立面向长期产品展开的基础。",
      initiatives_card_1_title: "从企划到实现",
      initiatives_card_1_body: "建立覆盖企划、美术制作与实现的一体化工作结构",
      initiatives_card_2_title: "本地化与运营准备",
      initiatives_card_2_body: "以日本市场为起点，完善运营导向与市场适配",
      initiatives_card_3_title: "多个项目的真实运作",
      initiatives_card_3_body: "不是一次性验证，而是在多个项目中持续推进",
      page_note: "代表项目"
    }
  }
};
